### ISSUE TITLE
Replace the gridapi with a configfile

### ISSUE THREAD

**Issue by robvanmieghem** [g8os/blockstor#111]
The gridapi becomes too slow resulting in timeout's in qemu when starting up a virtual machine. The vdisk info and storagecluster information should be read from a configfile instead of from the gridapi. This would also allow listing of the available exports which can now only be passed on the commandline. 
SIGHUP should still be supported to re-read the configuration.

@grimpy can you add the yaml format for the configfile here?

**Comment by grimpy** [comment]
```yaml
storageclusters:
  mycluster:
    dataStorage:
    - master:
        container: mycluster_data_0
        ip: 192.168.58.146
        port: 2000
        status: ready
      slave: null
    label: mycluster
    metadataStorage:
    - master:
        container: mycluster_metadata_0
        ip: 192.168.58.146
        port: 2001
        status: ready
      slave: null
    nodes:
    - '525400123456'
    status: ready
vdisks:
  myvdisk:
    blocksize: 4096
    id: myvdisk
    readOnly: true
    size: 10
    status: halted
    storagecluster: mycluster
    tlogStoragecluster: ''
    type: boot
```

multiple defnitions of vdisk and storageclusters are possible which correspond to multiple exports...

**Comment by robvanmieghem** [comment]
Dropped a few fields that are not relevant for the nbdserver: 

```yaml
storageclusters:
  mycluster:
    dataStorage:
    - master:
        ip: 192.168.58.146
        port: 2000
    label: mycluster
    metadataStorage:
    - master:
        ip: 192.168.58.146
        port: 2001
vdisks:
  myvdisk:
    blocksize: 4096
    readOnly: false
    size: 10
    storagecluster: mycluster
    tlogStoragecluster: ''
    type: boot
```
