### ISSUE TITLE
g8stor: replace copy/delete commands using config file support

### ISSUE THREAD

**Issue by GlenDC** [g8os/blockstor#204]
Currently we have 2 commands for both copy and delete (so 4 in total):

+ `g8stor copy deduped`;
+ `g8stor copy nondeduped`;
+ `g8stor delete deduped`;
+ `g8stor delete nondeduped `;

They:

+ do not currently support the config file (used also by nbdserver and tlogserver);
+ require specialized knowledge about the vdisks, how and where they are stored;
+ do currently not support copying/deleting to/from multiple ips at once (which is required, as data is usually spread over multiple data storage servers);

To resolve this issue we would introduce 2 new (additional) commands, which will use the config file, and handle all other details for you, which should simply copying and deleting vdisks a lot:

+ `g8stor copy vdisk`;
+ `g8stor delete vdisks`;

## Examples

`config.yml`:

```yaml
storageClusters:
  clusterA:
    dataStorage:
      - address: localhost:6379
    metaDataStorage:
      address: localhost:6379
  clusterB:
    dataStorage:
      - address: localhost:6380
    metaDataStorage:
      address: localhost:6380
vdisks:
  vdiskA:
    blockSize: 4096
    size: 1
    storageCluster: clusterA
    type: boot
  vdiskC:
    blockSize: 4096
    size: 1
    storageCluster: clusterB
    type: boot
```

to copy `vdiskA` as a new vdisk (`vdiskB`) on the _same_ storage cluster (`clusterA`), I would do:

```
$ g8stor copy vdisk vdiskA vdiskB
```

which would be the same as the more explicit version:

```
$ g8stor copy vdisk vdiskA vdiskB clusterA --config config.yml
```

to copy `vdiskA` as a new vdisk (`vdiskA`) on a _different_ storage cluster (`clusterB`), I would do:

```
$ g8stor copy vdisk vdiskA vdiskA clusterB
```

the following command would be illegal, and abort with an error:

```
$ g8stor copy vdisk vdiskA vdiskA
```

to delete all vdisks listed in the config file:

```
$ g8stor delete vdisks
```

which is the less explicit version of:

```
$ g8stor delete vdisks --config config.yml
```

to delete only 1 (or more) vdisks, rather then all, we can specify their id(s):

```
$ g8stor delete vdisks vdiskC --config.yml
```

with this knowledge we can write the first delete example even more explicit:

```
$ g8stor delete vdisks vdiskA vdiskC --config.yml
```

the following would succeed for the found vdisk, but log an error for the other vdisk as that one can't be found:

```
$ g8stor delete vdisks foo vdiskA # vdiskA will be deleted correctly, even though foo doesn't exist
```
